<a href="https://colab.research.google.com/github/jays-github2022/BSIS2-DV-Lab8-JAYSONB/blob/main/Lab8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **NUMPY**

In [1]:
# price list
price = [2, 1, 10] 
type(price)

list

In [2]:
# quantity list
quantity_sold = [17, 40, 1] 
type(quantity_sold)


list

In [ ]:
# performing calculations

price * quantity_sold

# You cannot perform calculations between lists

In [3]:
# In order to perform calculations, you have to convert a list into a numpy array

import numpy as np

In [4]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)
type(quantity_sold_array)

numpy.ndarray

In [5]:
price_array * quantity_sold_array

array([34, 40, 10])

In [6]:
cost_array = np.array([0.25, 0.50, 5.00])

In [7]:
profit_array = price_array - cost_array 
print(profit_array)

[1.75 0.5  5.  ]


In [8]:
profit_array > 2.00

array([False, False,  True])

In [9]:
price_array = price_array + [7] 
print(price_array)

[ 9  8 17]


In [10]:
price_array = price_array - [7]

In [11]:
np.append(price_array, 7) 
print(price_array)


[ 2  1 10]


In [12]:
price_array = np.append(price_array, [4.50, 3, 4, 9]) 
print(price_array)


[ 2.   1.  10.   4.5  3.   4.   9. ]


In [13]:
print(price_array.dtype)

float64


In [14]:
price_array = np.delete(price_array, -1) 
print(price_array)


[ 2.   1.  10.   4.5  3.   4. ]


In [15]:
price_array[2] = 12 
print(price_array)


[ 2.   1.  12.   4.5  3.   4. ]


In [16]:
print ("JAYSON BINABESE - BSIS 2")

JAYSON BINABESE - BSIS 2


In [17]:
print ("DATA VISUALIZATION")

DATA VISUALIZATION
